FROM python:3.7.8-alpine3.12
RUN apk upgrade && \
apk update && \
echo @latest-stable http://nl.alpinelinux.org/alpine/latest-stable/community >> /etc/apk/repositories && \
echo @latest-stable http://nl.alpinelinux.org/alpine/latest-stable/main >> /etc/apk/repositories && \
apk --no-cache add chromium\
 chromium-chromedriver \
 tzdata \
 xvfb

ENV TZ=Asia/Bangkok
COPY requirements.txt /tmp/requirements.txt
RUN pip3 install -r /tmp/requirements.txt

CMD ["sh","./run_tests.sh"]
